export const VERIFIED_AT = '2026-09-06';
export const PLANS = [
  { id: 'codex', name: 'Codex / ChatGPT', access: 'ChatGPT plan login or separately billed API credentials',
    tiers: ['Plus', 'Pro', 'Business', 'Enterprise / Edu'],
    note: 'Model access, included allowance and overages depend on the account. This app does not purchase credits or redeem resets.',
    pricing: 'https://learn.chatgpt.com/docs/pricing', login: 'codex login', verifiedAt: VERIFIED_AT },
  { id: 'claude', name: 'Claude Code', access: 'Eligible Claude subscription or separately billed Anthropic API access',
    tiers: ['Pro: USD 20 monthly / USD 200 yearly', 'Max 5x: USD 100 monthly', 'Max 20x: USD 200 monthly', 'Team / Enterprise'],
    note: 'Snapshot list prices, before regional taxes. Usage is limited, not unlimited. Check checkout and account limits.',
    pricing: 'https://claude.com/pricing', login: 'claude', verifiedAt: VERIFIED_AT },
  { id: 'agy', name: 'Google Antigravity', access: 'Google account; quota varies by Google AI plan',
    tiers: ['Baseline access', 'Google AI Pro', 'Google AI Ultra'],
    note: 'Availability and third-party models vary by plan. Review the AI Credit Overages setting in Antigravity itself.',
    pricing: 'https://www.antigravity.google/docs/plans/', login: 'agy (follow vendor sign-in)', verifiedAt: VERIFIED_AT },
  { id: 'opencode', name: 'OpenCode', access: 'Connected providers, supported subscription paths, or configured local models',
    tiers: ['Provider-dependent'], note: 'Catalog entries do not grant access. Configure and authenticate the provider in OpenCode first. CLI compatibility is version-dependent.',
    pricing: 'https://opencode.ai/docs/providers', login: 'opencode auth login', verifiedAt: VERIFIED_AT },
  { id: 'openrouter', name: 'OpenRouter', access: 'Provider API balance; use through a compatible configured CLI such as OpenCode',
    tiers: ['Free model endpoints with limits', 'Usage-priced endpoints'],
    note: 'A ChatGPT or Claude subscription does not pay OpenRouter bills. Refresh the catalog for advertised token rates.',
    pricing: 'https://openrouter.ai/docs/guides/overview/models', login: 'Authenticate OpenRouter in the selected CLI', verifiedAt: VERIFIED_AT },
  { id: 'local', name: 'Local / open-weight models', access: 'Local inference server configured in a compatible CLI',
    tiers: ['Hardware-dependent'], note: 'No cloud subscription is implied. Hardware, memory, electricity, model license and tool-calling support still matter.',
    pricing: 'https://opencode.ai/docs/providers', login: 'Configure your local provider in OpenCode or another supported CLI', verifiedAt: VERIFIED_AT },
  { id: 'cline', name: 'Cline CLI', access: 'Provider-dependent: account login or BYOK configured in Cline', tiers: ['Provider-dependent'],
    note: 'Cline is a client; model billing and availability come from the configured provider.', pricing: 'https://docs.cline.bot/running-models', login: 'cline auth', verifiedAt: VERIFIED_AT },
  { id: 'commandcode', name: 'Command Code', access: 'Command Code account subscription or supported provider path', tiers: ['Free', 'Pro', 'Max tiers'],
    note: 'Shared-pool and per-model allowances can differ. Inspect the account page before a long fleet run.', pricing: 'https://commandcode.ai/pricing', login: 'cmd login (cmdc on Windows)', verifiedAt: VERIFIED_AT },
  { id: 'grok', name: 'Grok Build', access: 'Grok/xAI account or provider-specific billing', tiers: ['Provider-dependent'],
    note: 'Use the CLI model listing and account billing page; catalog presence is not entitlement.', pricing: 'https://x.ai/api', login: 'grok login', verifiedAt: VERIFIED_AT },
  { id: 'kimi', name: 'Kimi Code', access: 'Kimi OAuth or configured API provider', tiers: ['Provider-dependent'],
    note: 'The runtime never reads Kimi provider files because they may contain credentials.', pricing: 'https://www.kimi.com/code', login: 'kimi (follow provider login)', verifiedAt: VERIFIED_AT },
  { id: 'qoder', name: 'Qoder CLI', access: 'Qoder account credits or supported BYOK providers', tiers: ['Free', 'Pro: USD 20 monthly', 'Pro+: USD 60 monthly', 'Ultra: USD 200 monthly'],
    note: 'Snapshot list prices before tax. Premium credits, basic-model fallbacks and packs have separate limits.', pricing: 'https://docs.qoder.com/account/pricing', login: 'qodercli /login', verifiedAt: VERIFIED_AT },
  { id: 'vibe', name: 'Mistral Vibe', access: 'Mistral plan allowance, PAYG setting or API credits', tiers: ['Free limited access', 'Pro', 'Team / Enterprise'],
    note: 'Subscription allowance and API credits are distinct. Review PAYG settings before long runs.', pricing: 'https://mistral.ai/pricing/', login: 'vibe (follow vendor login)', verifiedAt: VERIFIED_AT },
  { id: 'cursor', name: 'Cursor Agent', access: 'Cursor subscription and its enabled model pool', tiers: ['Hobby', 'Pro', 'Business / Enterprise'],
    note: 'Models and usage multipliers can change by plan. Use cursor-agent models for exact selectable IDs.', pricing: 'https://www.cursor.com/pricing', login: 'cursor-agent login', verifiedAt: VERIFIED_AT },
  { id: 'pi', name: 'Pi coding agent', access: 'Configured model providers and their credentials', tiers: ['Provider-dependent'],
    note: 'Pi is a client. The selected provider controls billing, limits and data handling.', pricing: 'https://github.com/badlogic/pi-mono', login: 'Configure a provider in Pi', verifiedAt: VERIFIED_AT },
  { id: 'omp', name: 'Oh My Pi', access: 'Configured providers or supported subscription path', tiers: ['Provider-dependent'],
    note: 'Run omp models for its current catalog; provider billing remains authoritative.', pricing: 'https://github.com/can1357/oh-my-pi', login: 'Configure a provider in OMP', verifiedAt: VERIFIED_AT },
  { id: 'aider', name: 'Aider', access: 'BYOK or provider credentials', tiers: ['Provider-dependent'],
    note: 'Aider is open-source client software; the model provider charges separately.', pricing: 'https://aider.chat/docs/llms.html', login: 'Configure the provider key outside this runtime', verifiedAt: VERIFIED_AT },
  { id: 'copilot', name: 'GitHub Copilot CLI', access: 'Eligible GitHub Copilot plan', tiers: ['Free', 'Pro', 'Pro+', 'Business / Enterprise'],
    note: 'Included premium requests and model access vary by plan.', pricing: 'https://github.com/features/copilot/plans', login: 'copilot login', verifiedAt: VERIFIED_AT },
  { id: 'warp', name: 'Warp Agent', access: 'Warp account plan or supported service account', tiers: ['Free', 'Build', 'Business / Enterprise'],
    note: 'Cloud agent limits and model access vary by current Warp plan.', pricing: 'https://www.warp.dev/pricing', login: 'oz login', verifiedAt: VERIFIED_AT },
  { id: 'zcode', name: 'Z.AI ZCode', access: 'Z.ai Coding Plan or configured provider', tiers: ['Z.ai Coding Plan', 'Provider-dependent'],
    note: 'ZCode chooses its model in its own configuration; this relay does not expose a model dial.', pricing: 'https://zcode.z.ai/en/docs/configuration', login: 'Use ZCode account setup', verifiedAt: VERIFIED_AT },
];
export function plans(id) {
  const entries = id ? PLANS.filter(p => p.id === id) : PLANS;
  if (!entries.length) throw new Error('No verified plan entry for that provider; consult its official billing page.');
  return { verifiedAt: VERIFIED_AT, warning: 'Reference information, not live account balances or guaranteed model access. No subscriptions are bought or modified.', entries };
}
