import { mkdirSync, readFileSync, writeFileSync, renameSync, existsSync, unlinkSync, openSync, closeSync } from 'node:fs';
import { join, dirname, resolve, relative, isAbsolute } from 'node:path';
import { randomUUID, createHash } from 'node:crypto';

export const readJSON = path => JSON.parse(readFileSync(path, 'utf8').replace(/^\uFEFF/, ''));
export const hash = value => createHash('sha256').update(typeof value === 'string' ? value : JSON.stringify(value)).digest('hex');
export const now = () => new Date().toISOString();
export function atomicJSON(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  const temp = `${path}.${randomUUID()}.tmp`;
  writeFileSync(temp, `${JSON.stringify(value, null, 2)}\n`, { flag: 'wx' });
  renameSync(temp, path);
}
export function inside(root, path) {
  const target = resolve(root, path);
  const rel = relative(resolve(root), target);
  if (rel === '..' || rel.startsWith('../') || rel.startsWith('..\\') || isAbsolute(rel)) throw new Error(`Path outside project: ${path}`);
  return target;
}
export function projectDir(root) { return join(resolve(root), '.tvc'); }
export function loadProject(root) {
  const path = join(projectDir(root), 'project.json');
  if (!existsSync(path)) throw new Error('No TVC project. Run tvc init <directory> --brief <file>.');
  const state = readJSON(path);
  if (state.schema !== 'tvc-project.v1') throw new Error('Unsupported project schema.');
  return state;
}
export function saveProject(root, state) {
  state.updatedAt = now();
  atomicJSON(join(projectDir(root), 'project.json'), state);
  const stateDir = join(root, '_state');
  mkdirSync(stateDir, { recursive: true });
  const lines = [`# Project: ${state.name}`, '', `Stage: ${state.stage}`, `Updated: ${state.updatedAt}`, '',
    '## Tasks', '', '| ID | Role | Status |', '|---|---|---|',
    ...state.tasks.map(t => `| ${t.id} | ${t.role} | ${t.status} |`), '', '## Decisions', '',
    ...state.decisions.map(d => `- ${d.id} [${d.status}]: ${d.question || d.value}`), '',
    '## Locks', '', ...Object.entries(state.locks).map(([k, v]) => `- ${k}: ${JSON.stringify(v)}`), '',
    'Authoritative state: .tvc/project.json. This view is regenerated by the CLI.', ''];
  writeFileSync(join(stateDir, 'project-state.md'), lines.join('\n'));
}
export function createProject(root, name, brief, config) {
  mkdirSync(root, { recursive: true });
  if (existsSync(join(projectDir(root), 'project.json'))) throw new Error('Project already exists.');
  const state = { schema: 'tvc-project.v1', name, createdAt: now(), stage: 'intake', brief,
    briefRevision: 1, config, tasks: [], decisions: [], locks: {}, entities: {}, changes: [],
    runs: [], debates: [], plan: null, reviewRound: 0, reconciliation: null, reviews: {}, assets: [] };
  saveProject(root, state);
  return state;
}
export async function withProjectLock(root, fn) {
  mkdirSync(projectDir(root), { recursive: true });
  const path = join(projectDir(root), 'run.lock');
  const token = randomUUID();
  let fd;
  try { fd = openSync(path, 'wx'); }
  catch (error) {
    if (error.code !== 'EEXIST') throw error;
    let lock;
    try { lock = readJSON(path); } catch { throw new Error('Unreadable run lock; inspect .tvc/run.lock before recovery.'); }
    let alive = true;
    try { process.kill(lock.pid, 0); } catch (e) { if (e.code === 'ESRCH') alive = false; }
    if (alive) throw new Error(`Another command owns the project (PID ${lock.pid}).`);
    unlinkSync(path);
    return withProjectLock(root, fn);
  }
  try {
    writeFileSync(fd, JSON.stringify({ pid: process.pid, token, createdAt: now() }));
    closeSync(fd); fd = undefined;
    return await fn();
  } finally {
    if (fd !== undefined) closeSync(fd);
    if (existsSync(path) && readJSON(path).token === token) unlinkSync(path);
  }
}
